require("taskbar.items.widgets.battery")
require("taskbar.items.widgets.volume")
require("taskbar.items.widgets.wifi")
require("taskbar.items.widgets.cpu")
require("taskbar.items.widgets.wallpaper")
require("taskbar.items.widgets.skhd")
